window.YSOAM_TRIPS = {
  statusLabels: {
    created: 'Created',
    dispatched: 'Dispatched',
    transit: 'In Transit',
    complete: 'Complete',
    cancelled: 'Cancelled'
  },
  statusBadge: {
    created: 'badge-idle',
    dispatched: 'badge-transit',
    transit: 'badge-transit',
    complete: 'badge-active',
    cancelled: 'badge-offline'
  },
  routes: {
    mumbaiPune: [
      [19.076, 72.8777],
      [18.98, 73.12],
      [18.7557, 73.4091],
      [18.62, 73.65],
      [18.5204, 73.8567]
    ],
    puneMumbai: [
      [18.5204, 73.8567],
      [18.62, 73.65],
      [18.7557, 73.4091],
      [18.98, 73.12],
      [19.076, 72.8777]
    ],
    mumbaiNashik: [
      [19.076, 72.8777],
      [19.35, 73.05],
      [19.72, 73.35],
      [19.9975, 73.7898]
    ],
    lonavalaPune: [
      [18.7557, 73.4091],
      [18.68, 73.55],
      [18.58, 73.72],
      [18.5204, 73.8567]
    ],
    thaneKalyan: [
      [19.2183, 72.9781],
      [19.228, 73.05],
      [19.2403, 73.1305]
    ]
  },
  trips: [
    {
      id: 'TRP-2026-0142',
      origin: 'Mumbai',
      destination: 'Pune',
      route: 'Mumbai → Pune',
      vehicleId: 'MH-12-AB-1234',
      driver: 'Rajesh K.',
      customer: 'Acme Logistics',
      status: 'complete',
      startAt: '08 Jun 2026, 06:12',
      endAt: '08 Jun 2026, 14:35',
      distance: 148,
      duration: '8h 23m',
      avgSpeed: 52,
      revenue: 4500,
      fuel: 2100,
      advance: 500,
      maintenance: 450,
      margin: 32,
      marginAmount: 1450,
      stops: 2,
      idleTime: '42m',
      loadType: 'General cargo',
      invoiceId: 'INV-2026-0088',
      routeKey: 'mumbaiPune',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0141',
      origin: 'Pune',
      destination: 'Mumbai',
      route: 'Pune → Mumbai',
      vehicleId: 'MH-22-LM-6789',
      driver: 'Suresh P.',
      customer: 'BlueDart Freight',
      status: 'transit',
      startAt: '08 Jun 2026, 11:05',
      endAt: null,
      distance: 96,
      duration: '4h 10m',
      avgSpeed: 58,
      revenue: 3800,
      fuel: null,
      advance: 400,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 1,
      idleTime: '18m',
      loadType: 'Express parcel',
      invoiceId: null,
      routeKey: 'puneMumbai',
      steps: ['created', 'dispatched', 'transit']
    },
    {
      id: 'TRP-2026-0140',
      origin: 'Mumbai',
      destination: 'Nashik',
      route: 'Mumbai → Nashik',
      vehicleId: 'MH-01-EF-7890',
      driver: 'Amit V.',
      customer: 'Reliance Retail',
      status: 'dispatched',
      startAt: '08 Jun 2026, 13:40',
      endAt: null,
      distance: 0,
      duration: '—',
      avgSpeed: null,
      revenue: 5200,
      fuel: null,
      advance: 600,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'FMCG',
      invoiceId: null,
      routeKey: 'mumbaiNashik',
      steps: ['created', 'dispatched']
    },
    {
      id: 'TRP-2026-0139',
      origin: 'Lonavala',
      destination: 'Pune',
      route: 'Lonavala → Pune',
      vehicleId: 'MH-12-JK-2345',
      driver: 'Vikram S.',
      customer: 'Mahindra Parts',
      status: 'transit',
      startAt: '08 Jun 2026, 09:22',
      endAt: null,
      distance: 64,
      duration: '2h 05m',
      avgSpeed: 49,
      revenue: 2900,
      fuel: null,
      advance: 300,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '12m',
      loadType: 'Auto parts',
      invoiceId: null,
      routeKey: 'lonavalaPune',
      steps: ['created', 'dispatched', 'transit']
    },
    {
      id: 'TRP-2026-0138',
      origin: 'Thane',
      destination: 'Kalyan',
      route: 'Thane → Kalyan',
      vehicleId: 'MH-43-NO-0123',
      driver: 'Deepak M.',
      customer: 'Local distributor',
      status: 'complete',
      startAt: '07 Jun 2026, 15:10',
      endAt: '07 Jun 2026, 16:45',
      distance: 22,
      duration: '1h 35m',
      avgSpeed: 28,
      revenue: 1800,
      fuel: 980,
      advance: 200,
      maintenance: 320,
      margin: -4,
      marginAmount: -70,
      stops: 1,
      idleTime: '28m',
      loadType: 'Mixed',
      invoiceId: 'INV-2026-0085',
      routeKey: 'thaneKalyan',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0137',
      origin: 'Mumbai',
      destination: 'Pune',
      route: 'Mumbai → Pune',
      vehicleId: 'MH-15-PQ-4567',
      driver: '—',
      customer: 'Tata Steel',
      status: 'created',
      startAt: '09 Jun 2026, 05:00',
      endAt: null,
      distance: 0,
      duration: '—',
      avgSpeed: null,
      revenue: 4800,
      fuel: null,
      advance: null,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'Steel coils',
      invoiceId: null,
      routeKey: 'mumbaiPune',
      steps: ['created']
    },
    {
      id: 'TRP-2026-0136',
      origin: 'Pune',
      destination: 'Mumbai',
      route: 'Pune → Mumbai',
      vehicleId: 'MH-14-CD-5678',
      driver: '—',
      customer: 'Amazon FC',
      status: 'complete',
      startAt: '06 Jun 2026, 07:30',
      endAt: '06 Jun 2026, 15:12',
      distance: 152,
      duration: '7h 42m',
      avgSpeed: 54,
      revenue: 4200,
      fuel: 1950,
      advance: 450,
      maintenance: 380,
      margin: 28,
      marginAmount: 1420,
      stops: 2,
      idleTime: '35m',
      loadType: 'E-commerce',
      invoiceId: 'INV-2026-0082',
      routeKey: 'puneMumbai',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0135',
      origin: 'Mumbai',
      destination: 'Nashik',
      route: 'Mumbai → Nashik',
      vehicleId: 'MH-04-HI-3456',
      driver: '—',
      customer: 'Pharma Express',
      status: 'cancelled',
      startAt: '05 Jun 2026, 10:00',
      endAt: '05 Jun 2026, 10:45',
      distance: 8,
      duration: '45m',
      avgSpeed: 0,
      revenue: 0,
      fuel: 420,
      advance: 0,
      maintenance: 0,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'Pharma',
      invoiceId: null,
      routeKey: 'mumbaiNashik',
      steps: ['created']
    }
  ]
};
