window.YSOAM_TRIPS = {
  statusLabels: {
    created: 'Created',
    dispatched: 'Dispatched',
    transit: 'In Transit',
    complete: 'Complete',
    cancelled: 'Cancelled'
  },
  statusBadge: {
    created: 'badge-idle',
    dispatched: 'badge-transit',
    transit: 'badge-transit',
    complete: 'badge-active',
    cancelled: 'badge-offline'
  },
  routes: {
    mumbaiPune: [
      [19.076, 72.8777],
      [18.98, 73.12],
      [18.7557, 73.4091],
      [18.62, 73.65],
      [18.5204, 73.8567]
    ],
    puneMumbai: [
      [18.5204, 73.8567],
      [18.62, 73.65],
      [18.7557, 73.4091],
      [18.98, 73.12],
      [19.076, 72.8777]
    ],
    mumbaiNashik: [
      [19.076, 72.8777],
      [19.35, 73.05],
      [19.72, 73.35],
      [19.9975, 73.7898]
    ],
    lonavalaPune: [
      [18.7557, 73.4091],
      [18.68, 73.55],
      [18.58, 73.72],
      [18.5204, 73.8567]
    ],
    thaneKalyan: [
      [19.2183, 72.9781],
      [19.228, 73.05],
      [19.2403, 73.1305]
    ]
  },
  trips: [
    {
      id: 'TRP-2026-0142',
      origin: 'Mumbai',
      destination: 'Pune',
      route: 'Mumbai → Pune',
      vehicleId: 'MH-12-AB-1234',
      driver: 'Rajesh K.',
      customer: 'Acme Logistics',
      status: 'complete',
      startAt: '08 Jun 2026, 06:12',
      endAt: '08 Jun 2026, 14:35',
      distance: 148,
      duration: '8h 23m',
      avgSpeed: 52,
      revenue: 4500,
      fuel: 2100,
      advance: 500,
      maintenance: 450,
      margin: 32,
      marginAmount: 1450,
      stops: 2,
      idleTime: '42m',
      loadType: 'General cargo',
      invoiceId: 'INV-2026-0088',
      routeKey: 'mumbaiPune',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0141',
      origin: 'Pune',
      destination: 'Mumbai',
      route: 'Pune → Mumbai',
      vehicleId: 'MH-22-LM-6789',
      driver: 'Suresh P.',
      customer: 'BlueDart Freight',
      status: 'transit',
      startAt: '08 Jun 2026, 11:05',
      endAt: null,
      distance: 96,
      duration: '4h 10m',
      avgSpeed: 58,
      revenue: 3800,
      fuel: null,
      advance: 400,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 1,
      idleTime: '18m',
      loadType: 'Express parcel',
      invoiceId: null,
      routeKey: 'puneMumbai',
      steps: ['created', 'dispatched', 'transit']
    },
    {
      id: 'TRP-2026-0140',
      origin: 'Mumbai',
      destination: 'Nashik',
      route: 'Mumbai → Nashik',
      vehicleId: 'MH-01-EF-7890',
      driver: 'Amit V.',
      customer: 'Reliance Retail',
      status: 'dispatched',
      startAt: '08 Jun 2026, 13:40',
      endAt: null,
      distance: 0,
      duration: '—',
      avgSpeed: null,
      revenue: 5200,
      fuel: null,
      advance: 600,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'FMCG',
      invoiceId: null,
      routeKey: 'mumbaiNashik',
      steps: ['created', 'dispatched']
    },
    {
      id: 'TRP-2026-0139',
      origin: 'Lonavala',
      destination: 'Pune',
      route: 'Lonavala → Pune',
      vehicleId: 'MH-12-JK-2345',
      driver: 'Vikram S.',
      customer: 'Mahindra Parts',
      status: 'transit',
      startAt: '08 Jun 2026, 09:22',
      endAt: null,
      distance: 64,
      duration: '2h 05m',
      avgSpeed: 49,
      revenue: 2900,
      fuel: null,
      advance: 300,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '12m',
      loadType: 'Auto parts',
      invoiceId: null,
      routeKey: 'lonavalaPune',
      steps: ['created', 'dispatched', 'transit']
    },
    {
      id: 'TRP-2026-0138',
      origin: 'Thane',
      destination: 'Kalyan',
      route: 'Thane → Kalyan',
      vehicleId: 'MH-43-NO-0123',
      driver: 'Deepak M.',
      customer: 'Local distributor',
      status: 'complete',
      startAt: '07 Jun 2026, 15:10',
      endAt: '07 Jun 2026, 16:45',
      distance: 22,
      duration: '1h 35m',
      avgSpeed: 28,
      revenue: 1800,
      fuel: 980,
      advance: 200,
      maintenance: 320,
      margin: -4,
      marginAmount: -70,
      stops: 1,
      idleTime: '28m',
      loadType: 'Mixed',
      invoiceId: 'INV-2026-0085',
      routeKey: 'thaneKalyan',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0137',
      origin: 'Mumbai',
      destination: 'Pune',
      route: 'Mumbai → Pune',
      vehicleId: 'MH-15-PQ-4567',
      driver: '—',
      customer: 'Tata Steel',
      status: 'created',
      startAt: '09 Jun 2026, 05:00',
      endAt: null,
      distance: 0,
      duration: '—',
      avgSpeed: null,
      revenue: 4800,
      fuel: null,
      advance: null,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'Steel coils',
      invoiceId: null,
      routeKey: 'mumbaiPune',
      steps: ['created']
    },
    {
      id: 'TRP-2026-0136',
      origin: 'Pune',
      destination: 'Mumbai',
      route: 'Pune → Mumbai',
      vehicleId: 'MH-14-CD-5678',
      driver: '—',
      customer: 'Amazon FC',
      status: 'complete',
      startAt: '06 Jun 2026, 07:30',
      endAt: '06 Jun 2026, 15:12',
      distance: 152,
      duration: '7h 42m',
      avgSpeed: 54,
      revenue: 4200,
      fuel: 1950,
      advance: 450,
      maintenance: 380,
      margin: 28,
      marginAmount: 1420,
      stops: 2,
      idleTime: '35m',
      loadType: 'E-commerce',
      invoiceId: 'INV-2026-0082',
      routeKey: 'puneMumbai',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0135',
      origin: 'Mumbai',
      destination: 'Nashik',
      route: 'Mumbai → Nashik',
      vehicleId: 'MH-04-HI-3456',
      driver: '—',
      customer: 'Pharma Express',
      status: 'cancelled',
      startAt: '05 Jun 2026, 10:00',
      endAt: '05 Jun 2026, 10:45',
      distance: 8,
      duration: '45m',
      avgSpeed: 0,
      revenue: 0,
      fuel: 420,
      advance: 0,
      maintenance: 0,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'Pharma',
      invoiceId: null,
      routeKey: 'mumbaiNashik',
      steps: ['created']
    },
    {
      id: 'TRP-2026-0134',
      origin: 'Mumbai',
      destination: 'Pune',
      route: 'Mumbai → Pune',
      vehicleId: 'MH-12-AB-1234',
      driver: 'Rajesh K.',
      customer: 'Flipkart Hub',
      status: 'complete',
      startAt: '04 Jun 2026, 06:45',
      endAt: '04 Jun 2026, 14:20',
      distance: 149,
      duration: '7h 35m',
      avgSpeed: 53,
      revenue: 4600,
      fuel: 2050,
      advance: 500,
      maintenance: 420,
      margin: 30,
      marginAmount: 1630,
      stops: 1,
      idleTime: '30m',
      loadType: 'E-commerce',
      invoiceId: 'INV-2026-0080',
      routeKey: 'mumbaiPune',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0133',
      origin: 'Pune',
      destination: 'Mumbai',
      route: 'Pune → Mumbai',
      vehicleId: 'MH-07-RS-8901',
      driver: 'Suresh P.',
      customer: 'DHL Supply Chain',
      status: 'complete',
      startAt: '03 Jun 2026, 08:10',
      endAt: '03 Jun 2026, 16:05',
      distance: 151,
      duration: '7h 55m',
      avgSpeed: 51,
      revenue: 4100,
      fuel: 1980,
      advance: 450,
      maintenance: 400,
      margin: 25,
      marginAmount: 1270,
      stops: 2,
      idleTime: '38m',
      loadType: 'General cargo',
      invoiceId: 'INV-2026-0078',
      routeKey: 'puneMumbai',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0132',
      origin: 'Lonavala',
      destination: 'Pune',
      route: 'Lonavala → Pune',
      vehicleId: 'MH-12-JK-2345',
      driver: 'Vikram S.',
      customer: 'Bajaj Auto',
      status: 'complete',
      startAt: '02 Jun 2026, 10:15',
      endAt: '02 Jun 2026, 12:30',
      distance: 66,
      duration: '2h 15m',
      avgSpeed: 48,
      revenue: 2700,
      fuel: 1180,
      advance: 250,
      maintenance: 280,
      margin: 22,
      marginAmount: 990,
      stops: 0,
      idleTime: '10m',
      loadType: 'Auto parts',
      invoiceId: 'INV-2026-0076',
      routeKey: 'lonavalaPune',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0131',
      origin: 'Mumbai',
      destination: 'Nashik',
      route: 'Mumbai → Nashik',
      vehicleId: 'MH-01-EF-7890',
      driver: 'Amit V.',
      customer: 'Godrej Consumer',
      status: 'complete',
      startAt: '01 Jun 2026, 07:00',
      endAt: '01 Jun 2026, 11:45',
      distance: 168,
      duration: '4h 45m',
      avgSpeed: 55,
      revenue: 5100,
      fuel: 2280,
      advance: 550,
      maintenance: 480,
      margin: 35,
      marginAmount: 1790,
      stops: 1,
      idleTime: '22m',
      loadType: 'FMCG',
      invoiceId: 'INV-2026-0074',
      routeKey: 'mumbaiNashik',
      steps: ['created', 'dispatched', 'transit', 'complete']
    },
    {
      id: 'TRP-2026-0130',
      origin: 'Mumbai',
      destination: 'Pune',
      route: 'Mumbai → Pune',
      vehicleId: 'MH-14-CD-5678',
      driver: 'Deepak M.',
      customer: 'ITC Ltd',
      status: 'transit',
      startAt: '08 Jun 2026, 14:20',
      endAt: null,
      distance: 72,
      duration: '3h 05m',
      avgSpeed: 56,
      revenue: 4400,
      fuel: null,
      advance: 480,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '8m',
      loadType: 'FMCG',
      invoiceId: null,
      routeKey: 'mumbaiPune',
      steps: ['created', 'dispatched', 'transit']
    },
    {
      id: 'TRP-2026-0129',
      origin: 'Pune',
      destination: 'Mumbai',
      route: 'Pune → Mumbai',
      vehicleId: 'MH-22-LM-6789',
      driver: 'Rajesh K.',
      customer: 'Swiggy Instamart',
      status: 'dispatched',
      startAt: '08 Jun 2026, 15:30',
      endAt: null,
      distance: 0,
      duration: '—',
      avgSpeed: null,
      revenue: 3600,
      fuel: null,
      advance: 350,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'Perishables',
      invoiceId: null,
      routeKey: 'puneMumbai',
      steps: ['created', 'dispatched']
    },
    {
      id: 'TRP-2026-0128',
      origin: 'Thane',
      destination: 'Kalyan',
      route: 'Thane → Kalyan',
      vehicleId: 'MH-43-NO-0123',
      driver: 'Vikram S.',
      customer: 'Local distributor',
      status: 'transit',
      startAt: '08 Jun 2026, 12:00',
      endAt: null,
      distance: 14,
      duration: '45m',
      avgSpeed: 32,
      revenue: 1600,
      fuel: null,
      advance: 150,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 1,
      idleTime: '15m',
      loadType: 'Mixed',
      invoiceId: null,
      routeKey: 'thaneKalyan',
      steps: ['created', 'dispatched', 'transit']
    },
    {
      id: 'TRP-2026-0127',
      origin: 'Mumbai',
      destination: 'Pune',
      route: 'Mumbai → Pune',
      vehicleId: 'MH-15-PQ-4567',
      driver: '—',
      customer: 'JSW Steel',
      status: 'created',
      startAt: '09 Jun 2026, 04:30',
      endAt: null,
      distance: 0,
      duration: '—',
      avgSpeed: null,
      revenue: 5500,
      fuel: null,
      advance: null,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'Steel coils',
      invoiceId: null,
      routeKey: 'mumbaiPune',
      steps: ['created']
    },
    {
      id: 'TRP-2026-0126',
      origin: 'Mumbai',
      destination: 'Nashik',
      route: 'Mumbai → Nashik',
      vehicleId: 'MH-04-HI-3456',
      driver: '—',
      customer: 'Sun Pharma',
      status: 'created',
      startAt: '10 Jun 2026, 06:00',
      endAt: null,
      distance: 0,
      duration: '—',
      avgSpeed: null,
      revenue: 4900,
      fuel: null,
      advance: null,
      maintenance: null,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'Pharma',
      invoiceId: null,
      routeKey: 'mumbaiNashik',
      steps: ['created']
    },
    {
      id: 'TRP-2026-0125',
      origin: 'Lonavala',
      destination: 'Pune',
      route: 'Lonavala → Pune',
      vehicleId: 'MH-12-JK-2345',
      driver: 'Suresh P.',
      customer: 'Volkswagen Pune',
      status: 'cancelled',
      startAt: '30 May 2026, 09:00',
      endAt: '30 May 2026, 09:30',
      distance: 0,
      duration: '30m',
      avgSpeed: 0,
      revenue: 0,
      fuel: 180,
      advance: 0,
      maintenance: 0,
      margin: null,
      marginAmount: null,
      stops: 0,
      idleTime: '—',
      loadType: 'Auto parts',
      invoiceId: null,
      routeKey: 'lonavalaPune',
      steps: ['created']
    },
    {
      id: 'TRP-2026-0124',
      origin: 'Pune',
      destination: 'Mumbai',
      route: 'Pune → Mumbai',
      vehicleId: 'MH-12-AB-1234',
      driver: 'Rajesh K.',
      customer: 'FedEx Freight',
      status: 'complete',
      startAt: '29 May 2026, 05:50',
      endAt: '29 May 2026, 13:40',
      distance: 150,
      duration: '7h 50m',
      avgSpeed: 52,
      revenue: 4300,
      fuel: 2010,
      advance: 480,
      maintenance: 410,
      margin: 27,
      marginAmount: 1400,
      stops: 2,
      idleTime: '40m',
      loadType: 'Express parcel',
      invoiceId: 'INV-2026-0070',
      routeKey: 'puneMumbai',
      steps: ['created', 'dispatched', 'transit', 'complete']
    }
  ],
  statusOptions: [
    { id: 'created', label: 'Created' },
    { id: 'dispatched', label: 'Dispatched' },
    { id: 'transit', label: 'In Transit' },
    { id: 'complete', label: 'Complete' },
    { id: 'cancelled', label: 'Cancelled' }
  ],
  routeOptions: [
    { id: 'Mumbai → Pune', label: 'Mumbai → Pune' },
    { id: 'Pune → Mumbai', label: 'Pune → Mumbai' },
    { id: 'Mumbai → Nashik', label: 'Mumbai → Nashik' },
    { id: 'Lonavala → Pune', label: 'Lonavala → Pune' },
    { id: 'Thane → Kalyan', label: 'Thane → Kalyan' }
  ],
  getById: function (id) {
    return this.trips.filter(function (t) { return t.id === id; })[0] || null;
  },
  canPlayback: function (trip) {
    return trip.routeKey && (trip.status === 'complete' || trip.status === 'transit') && trip.distance > 0;
  },
  formatMargin: function (trip) {
    if (trip.margin === null || trip.margin === undefined) return '—';
    var cls = trip.margin >= 0 ? 'trip-ops-margin--pos' : 'trip-ops-margin--neg';
    return '<span class="trip-ops-margin ' + cls + ' tabular-nums">' + trip.margin + '%</span>';
  }
};
